---
title: "base_network"
author: "Brian Jo Hsuan Lee"
date: "5/5/2022"
output: pdf_document
---
```{r}
library(tidyverse)
library(igraph)
```

```{r}
file_path = "~/Downloads/TCGA/"
tumor_f = list.files(path = file_path, pattern = "T.tsv")
norm_f = list.files(path = file_path, pattern = "N.tsv")
gene_sample = read_lines(file = "~/Desktop/Columbia/Spring_2022/P8139-Statistical_Genetic_Modeling/Project/gene_sample_ind") %>% 
  as.numeric()
gene_int = read_csv("~/Desktop/Columbia/Spring_2022/P8139-Statistical_Genetic_Modeling/Project/gene_int")
gene_list = read_lines(file = "~/Desktop/Columbia/Spring_2022/P8139-Statistical_Genetic_Modeling/Project/gene_list")
S_0 = read_csv("~/Desktop/Columbia/Spring_2022/P8139-Statistical_Genetic_Modeling/Project/s0_zero_matrix")
```

```{r}
gene_int_undir = graph.data.frame(gene_int, directed=F)
S_0_alt = get.adjacency(gene_int_undir, attr="combined_score", sparse=F)

miss_col = setdiff(colnames(S_0), colnames(S_0_alt))
new_col = rep(NA, nrow(S_0_alt))
for(i in seq_len(length(miss_col))){
  S_0_alt =
    S_0_alt %>% 
    cbind(new_col)
  colnames(S_0_alt)[ncol(S_0_alt)] = miss_col[i]
}

miss_row = setdiff(colnames(S_0), rownames(S_0_alt))
new_row = rep(NA, ncol(S_0_alt))
for(i in seq_len(length(miss_row))){
  S_0_alt =
    S_0_alt %>% 
    rbind(new_row)
  rownames(S_0_alt)[nrow(S_0_alt)] = miss_row[i]
}

S_0_alt = S_0_alt[colnames(S_0), colnames(S_0)]
S_0_alt[is.na(S_0_alt)] = 0

sum(S_0_alt) == 2*sum(gene_int$combined_score)

S_0_alt = S_0_alt %>% data.frame()

write_csv(S_0_alt, file="~/Desktop/Columbia/Spring_2022/P8139-Statistical_Genetic_Modeling/Project/base_network")
```