---
title: "gene_sample_gene_network"
author: "Brian Jo Hsuan Lee"
date: "5/5/2022"
output: pdf_document
---

```{r}
library(tidyverse)
library(STRINGdb)
library(hash)
library(readxl)
library(readr)
library(hash)
```

read in the first BRCA tumor sample file
```{r}
file_path = "~/Downloads/TCGA/"
tumor_f = list.files(path = file_path, pattern = "T.tsv")

sample_data = 
  read_delim(file = paste(file_path, tumor_f[1], sep = ""), 
             skip = 1, delim = "\t", quote = "") %>% 
  filter(!row_number() %in% c(1:4)) %>% 
  select(gene_name, tpm_unstranded) %>% 
  data.frame()
```

the STRING general network maps close to 19000 genes in the BRCA data. save the list of mapped genes
```{r}
string_db = STRINGdb$new(version="11", species=9606, score_threshold=200, input_directory="")
example_mapped = string_db$map(sample_data, "gene_name", removeUnmappedRows = T) %>% distinct(gene_name, .keep_all = TRUE) %>% distinct(STRING_id, .keep_all = TRUE)
gene_list = example_mapped$gene_name
write_lines(gene_list, file = "~/Desktop/Columbia/Spring_2022/P8139-Statistical_Genetic_Modeling/Project/gene_list")
length(example_mapped$gene_name)
```

randomly sample 600 mapped genes. save the indices of the sampled mapped genes
```{r}
set.seed(2022)
sample_data =
  sample_data %>% 
  mutate(gene_name = toupper(gene_name)) %>% 
  filter(gene_name %in% gene_list) %>% 
  distinct(gene_name, .keep_all = TRUE) %>% 
  arrange(gene_name)
gene_sample = sample(1:nrow(sample_data), 2000)
write_lines(gene_sample, file = "~/Desktop/Columbia/Spring_2022/P8139-Statistical_Genetic_Modeling/Project/gene_sample_ind")
```

build an empty matrix of sampled genes to fill in in the interactions later
```{r}
example_mapped_reduced = example_mapped[, c(1, 3)]
sample_data = inner_join(sample_data, example_mapped_reduced)
sample_brca_data = 
  arrange(sample_data) %>% 
  filter(row_number() %in% gene_sample)
h = hash()
for(i in seq_len(nrow(sample_brca_data))){
  h[[sample_brca_data[i, 3]]] = sample_brca_data[i, 1]
}
sample_brca_data$STRING_id
gene_int = string_db$get_interactions(sample_brca_data$STRING_id) %>% distinct(.keep_all = TRUE)

for(i in seq_len(nrow(gene_int))){
  print(i)
  gene_int[i, 1] = h[[gene_int[i, 1]]] 
  gene_int[i, 2] = h[[gene_int[i, 2]]] 
}

write_csv(gene_int, file = "~/Desktop/Columbia/Spring_2022/P8139-Statistical_Genetic_Modeling/Project/gene_int")

S_0 = matrix(0, nrow=length(sample_brca_data$gene_name), ncol=length(sample_brca_data$gene_name)) %>% data.frame()
col_names = sort(sample_brca_data$gene_name)
names(S_0) = col_names
rownames(S_0) = col_names
write_csv(S_0, file = "~/Desktop/Columbia/Spring_2022/P8139-Statistical_Genetic_Modeling/Project/s0_zero_matrix")
```

